# Generated by Django 3.2.9 on 2021-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_imagetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_test/images'),
        ),
    ]
