# Generated by Django 3.2.9 on 2021-12-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_imagetest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_test'),
        ),
    ]
