# Generated by Django 3.2.9 on 2021-12-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTest',
        ),
    ]
