# Generated by Django 3.2.9 on 2021-12-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='img_profile/default.jpg', upload_to='img_profile/'),
        ),
    ]
