# Generated by Django 3.2.9 on 2021-12-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
